### ISSUE TITLE
net.sf.json.JSONException: null object

### ISSUE THREAD

**Issue by cdgraff** [logstash/log4j-jsonevent-layout#30]
Hi guys, some idea why is not logging correctly and every exception have this error into the stacktrace,log?

2013-11-07 15:55:03,583 [http-apr-8080-exec-9] ERROR StackTrace  - Full Stack Trace:
net.sf.json.JSONException: null object
    at net.sf.json.JSONObject.verifyIsNull(JSONObject.java:2897)
    at net.sf.json.JSONObject.get(JSONObject.java:2110)
    at net.sf.json.JSONObject.get(JSONObject.java:2097)
    at com.site.UserController.formatJSONAvatarDTO(UserController.groovy:250)
    at com.site.UserController.saveUser(UserController.groovy:196)
    at com.googlecode.psiprobe.Tomcat70AgentValve.invoke(Tomcat70AgentValve.java:38)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:662)

Thanks for any advice

**Comment by lusis** [comment]
I don't think I've ever seen anything like this. I've done some tomcat tests recently to demo the appender and haven't run in to that. It sounds like MAYBE the json lib isn't handling a conversion properly though.

**Comment by shevie-bls** [comment]
When you try to serialize an JSONObject that has a property with a null value this happens
